name: CI/CD pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@main
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --cache-folder ~/.yarn

      - name: Check types
        run: yarn typecheck

      - name: Run linters
        run: yarn lint:ts

      # - name: Run tests and publish code coverage
      #   uses: paambaati/codeclimate-action@v2.7.5
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #   with:
      #     coverageCommand: yarn test
      #     coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov