name: CI/CD pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@main
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --cache-folder ~/.yarn

      - name: Check types
        run: yarn typecheck

      - name: Run linters
        run: yarn lint:ts && yarn lint:css:ci

      - name: Run tests and publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn test
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@main
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --cache-folder ~/.yarn
      
      - name: Prebuild
        run: yarn prebuild
        env:
          NEXT_PUBLIC_DOMAIN: ${{ secrets.DOMAIN }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      
      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_DOMAIN: ${{ secrets.DOMAIN }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

      - name: Export
        run: yarn export
        env:
          NEXT_PUBLIC_DOMAIN: ${{ secrets.DOMAIN }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

      - name: Upload production build artifact
        uses: actions/upload-artifact@main
        with:
          name: production-build
          path: out/

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Download production build artifact
        uses: actions/download-artifact@main
        with:
          name: production-build
          path: out

      - name: Use Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@main
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile --cache-folder ~/.yarn

      - name: Deploy to netlify
        run: npx netlify deploy --dir=out --message="$(git log -1 --pretty=format:'%s')" --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

